version: '3.7'

services:
  traefik:
    build: .
    image: arviantodwi/traefik
    restart: always
    networks:
      - traefik
    ports:
      # HTTP/S ports
      - '80:80'
      - '443:443'
      # TCP ports
      # -
    volumes:
      - ./traefik:/etc/traefik
    environment:
      TZ: ${TIMEZONE}

networks:
  traefik:
    driver: bridge
    name: traefik
