version: '3.7'

services:
  traefik:
    build:
      target: ${BUILD_TARGET}
    depends_on:
      - whoami
    volumes:
      - ./logs:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: containous/whoami
    networks:
      - traefik
